from makeFigure2_BasinMap import makeFigure2_BasinMap
from makeFigure3_HistoricalHMM import makeFigure3_HistoricalHMM
from makeFigure4_AllHMMparams import makeFigure4_AllHMMparams
from makeFigure5_AllFlowRanges import makeFigure5_AllFlowRanges
from makeFigure6_ShortageDistns import makeFigure6_ShortageDistns
from makeFigure7_VarianceDecomposition import makeFigure7_VarianceDecomposition
from makeFigure8_FactorMaps import makeFigure8_FactorMaps
from makeFigure9_RobustnessRanks import makeFigure9_RobustnessRanks
from makeFigureS1_GaussianFits import makeFigureS1_GaussianFits
from makeFigureS2_MarkovFits import makeFigureS2_MarkovFits
from makeFigureS3_SpatialCorrelation import makeFigureS3_SpatialCorrelation
from makeFigureS4_IrrigationModel import makeFigureS4_IrrigationModel
from makeFigureS5_ReconstructionModel import makeFigureS5_ReconstructionModel
from makeFigureS6_ReconstructionParams import makeFigureS6_ReconstructionParams
from makeFigureS7_VICerrorModel import makeFigureS7_VICerrorModel
from makeFigureS8_VICparams import makeFigureS8_VICparams
from makeFigureS9_FactorMaps2 import makeFigureS9_FactorMaps2
from makeFigureS10_SatisficingSurfaces import makeFigureS10_SatisficingSurfaces

makeFigure2_BasinMap()
makeFigure3_HistoricalHMM()
makeFigure4_AllHMMparams()
makeFigure5_AllFlowRanges()
makeFigure6_ShortageDistns()
makeFigure7_VarianceDecomposition()
makeFigure8_FactorMaps()
makeFigure9_RobustnessRanks()
makeFigureS1_GaussianFits()
makeFigureS2_MarkovFits()
makeFigureS3_SpatialCorrelation()
makeFigureS4_IrrigationModel()
makeFigureS5_ReconstructionModel()
makeFigureS6_ReconstructionParams()
makeFigureS7_VICerrorModel()
makeFigureS8_VICparams()
makeFigureS9_FactorMaps2()
makeFigureS10_SatisficingSurfaces()